# agents/chat_agent.py

from __future__ import annotations
from typing import Dict, List, Any
import pandas as pd
import json
from openai import OpenAI


# ============================================================
# CONTEXT BUILDER
# ============================================================

class ContextBuilder:

    @staticmethod
    def build(
        df: pd.DataFrame, 
        summary_text: str, 
        species_name: str
    ) -> str:
        """
        Builds structured context for the LLM using:
        - Key metrics from the dataframe
        - Aggregated statistics
        - Summary text generated by your pipeline
        """

        context: Dict[str, Any] = {
            "species": species_name,
            "total_records": int(len(df)),
        }

        # ------------------------------
        # ECOREGION COUNTS
        # ------------------------------
        if "ecoregion" in df.columns:
            context["ecoregion_counts"] = (
                df["ecoregion"].value_counts().to_dict()
            )
        else:
            context["ecoregion_counts"] = {}

        # ------------------------------
        # DATE COUNTS (if exist)
        # ------------------------------
        if "event_date" in df.columns:
            try:
                df["_event_year"] = pd.to_datetime(df["event_date"], errors="coerce").dt.year
                context["year_counts"] = (
                    df["_event_year"].value_counts().sort_index().dropna().astype(int).to_dict()
                )
            except Exception:
                context["year_counts"] = {}
        else:
            context["year_counts"] = {}

        # ------------------------------
        # BASIS OF RECORD
        # ------------------------------
        if "basisOfRecord" in df.columns:
            context["record_type_counts"] = (
                df["basisOfRecord"].value_counts().to_dict()
            )
        else:
            context["record_type_counts"] = {}

        # ------------------------------
        # GEO BOUNDS
        # ------------------------------
        def safe_float(x):
            try:
                return float(x)
            except:
                return None

        lat_col = next((c for c in df.columns if "lat" in c.lower()), None)
        lon_col = next((c for c in df.columns if "lon" in c.lower()), None)

        if lat_col and lon_col:
            context["geo_bounds"] = {
                "lat_min": safe_float(df[lat_col].min()),
                "lat_max": safe_float(df[lat_col].max()),
                "lon_min": safe_float(df[lon_col].min()),
                "lon_max": safe_float(df[lon_col].max()),
            }
        else:
            context["geo_bounds"] = {}

        # ------------------------------
        # SUMMARY TEXT
        # ------------------------------
        context["summary_text"] = summary_text

        # Convert to pretty JSON for LLM input
        return json.dumps(context, indent=2)


# ============================================================
# CHAT AGENT
# ============================================================

class ChatAgent:

    def __init__(self, api_key: str, model: str = "gpt-4o-mini"):
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def build_prompt(self, context_text: str, chat_history: List[Dict], user_message: str):
        """
        Builds the unified input for the LLM using the new Responses API format.
        """

        # SYSTEM MESSAGE: instructions + structured context
        system_content = f"""
You are AquaMind Chat — an assistant specialized in marine species.

You must answer using ONLY the structured data provided below.
You are allowed to:
- compute maxima, minima, counts, means
- identify which ecoregion/year has more/less observations
- summarize the provided statistics
- correct user assumptions if needed
- answer based on the summary_text provided in the context

You are NOT allowed to:
- make up data not present in the dataset
- guess or invent missing values
- speculate outside the context

================= CONTEXT DATA (JSON) =================
{context_text}
======================================================
"""

        messages = [
            {"role": "system", "content": system_content}
        ]

        # Add previous chat
        for msg in chat_history:
            messages.append({
                "role": msg["role"],
                "content": msg["content"]
            })

        # Add latest user question
        messages.append({"role": "user", "content": user_message})

        return messages

    def ask(self, context_text: str, chat_history: List[Dict], user_message: str) -> str:
        """
        Calls OpenAI responses.create() using the new API style.
        """

        input_list = self.build_prompt(context_text, chat_history, user_message)

        response = self.client.responses.create(
            model=self.model,
            input=input_list
        )

        return response.output_text